_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
                - 77
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
                - 77
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.2
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
callbacks:
    value:
        early_stopping:
            metric_name: valEpoch/avg_epi_node_mcc
            min_delta: 0
            minimize: false
            patience: 10
        lr_scheduler:
            kwargs:
                gamma: 0.9
                step_size: 10
            name: StepLR
            step: null
        model_checkpoint:
            k: 3
            metric_name: valEpoch/avg_epi_node_mcc
            minimize: false
            save_dir: /home/mansoor/antibody_design/epitope_prediction/epitope_pred/asepcode/../../results/asep/ckpts/20250113-221256
        model_checkpoint_edge:
            k: 3
            metric_name: valEpoch/avg_edge_index_bg_mcc
            minimize: false
            save_dir: /home/mansoor/antibody_design/epitope_prediction/epitope_pred/asepcode/../../results/asep/ckpts/edge/20250113-221256
dataset:
    value:
        ab:
            custom_embedding_method: null
            custom_embedding_method_src:
                method_name: embed_protbert
                name: ProtBERT
                script_path: asep/data/embedding/protbert.py
            embedding_model: esm2
        ag:
            custom_embedding_method: null
            custom_embedding_method_src:
                method_name: embed_esm2
                name: ESM2
                script_path: asep/data/embedding/esm2.py
            embedding_model: esm2
        name: asep
        node_feat_type: custom
        root: /home/mansoor/antibody_design/epitope_prediction/data
        split_idx: null
        split_method: null
hparams:
    value:
        act_list:
            - null
        batch_size: 128
        decoder:
            name: inner_prod
        dim_list:
            - 128
            - 64
        edge_cutoff: 0.5
        input_ab_act: relu
        input_ab_dim: 1024
        input_ag_act: relu
        input_ag_dim: 1024
        max_epochs: 300
        model_type: linear
        num_edge_cutoff: 3
        pos_weight: 100
        test_batch_size: 32
        train_batch_size: 128
        val_batch_size: 32
keep_interim_ckpts:
    value: true
logging_method:
    value: wandb
loss:
    value:
        edge_index_bg_rec_loss:
            kwargs:
                reduction: mean
                weight_tensor: 100
            name: edge_index_bg_rec_loss
            w: 1
        edge_index_bg_sum_loss:
            kwargs:
                thr: 40
            name: edge_index_bg_sum_loss
            w: 0.0003942821556421417
mode:
    value: train
num_threads:
    value: 4
optimizer:
    value:
        name: Adam
        params:
            lr: 0.001
            weight_decay: 0
seed:
    value: 3507901076
try_gpu:
    value: true
wandb_init:
    value:
        entity: alibilab-gsu
        group: train
        job_type: train
        notes: protbert-esm2
        project: retrain-walle-group
        tags:
            - train
work_dir:
    value: /home/mansoor/antibody_design/epitope_prediction/epitope_pred/asepcode
